### ISSUE TITLE
Add login functionality - Backend

### ISSUE THREAD

**Issue by jmpala** [jmpala/Imageboard#9]
The user needs to be able to login on the application

- [x]   Two new tables need to be created. One to store the user accounts and another to store the authorities(Roles) for the users  #10

- [x] Create User and Role dto, mapper, repository and service #11

- [x] The system need to configure Spring Security to fetch and validate the login data with the MySQL DB #12

- In case the user is not logged in, the view needs to display the register and login buttons on the navbar
- Configure Spring Security to serve a login page to the client
- Create the login.html and associate its form to provide the login credentials
- After logging in return the client to the same page
- In case the user is logged in, the view needs to display the logout button on the navbar
- Configure Spring Security to provide a logout endpoint

Useful resources:
* https://www.codejava.net/frameworks/spring-boot/form-authentication-with-jdbc-and-mysql
* https://www.codejava.net/frameworks/spring-boot/spring-boot-security-customize-login-and-logout
* https://www.javadevjournal.com/spring-security/spring-security-with-thymeleaf/
